#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-setuptools_scm
Version  : 3.2.0
Release  : 63
URL      : https://files.pythonhosted.org/packages/54/85/514ba3ca2a022bddd68819f187ae826986051d130ec5b972076e4f58a9f3/setuptools_scm-3.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/54/85/514ba3ca2a022bddd68819f187ae826986051d130ec5b972076e4f58a9f3/setuptools_scm-3.2.0.tar.gz
Summary  : the blessed package to manage your versions by scm tags
Group    : Development/Tools
License  : MIT
Requires: deprecated-setuptools_scm-license = %{version}-%{release}
Requires: deprecated-setuptools_scm-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : python3-dev
BuildRequires : setuptools-legacypython
BuildRequires : setuptools_scm

%description
setuptools_scm
===============
``setuptools_scm`` handles managing your Python package versions
in SCM metadata instead of declaring them as the version argument
or in a SCM managed file.

%package legacypython
Summary: legacypython components for the deprecated-setuptools_scm package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-setuptools_scm package.


%package license
Summary: license components for the deprecated-setuptools_scm package.
Group: Default

%description license
license components for the deprecated-setuptools_scm package.


%package python
Summary: python components for the deprecated-setuptools_scm package.
Group: Default

%description python
python components for the deprecated-setuptools_scm package.


%prep
%setup -q -n setuptools_scm-3.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554328294
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-setuptools_scm
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-setuptools_scm/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-setuptools_scm/LICENSE

%files python
%defattr(-,root,root,-)
